config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks" }
  resource :user, only: [] do
    resources :budgets, only: [:index]
  end
  get 'user/timezone', to: 'users#edit', as: 'edit_user_time_zone'
  resources :users, only: [:update]

  resources :budgets, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :categories, only: [:destroy, :show] do
    resources :expenses, only: [:create, :new]
  end

  resources :expenses, only: [:destroy]

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  has_many :category_budgets
  has_many :categories, :through => :category_budgets
  belongs_to :user
  has_many :categories, :dependent => :destroy
  #destroy instead of delete_all as we want to trigger the callback on category to delete all expenses associated with said category
  has_many :expenses, :through => :categories
  validates :name, :limit, :start_date, :end_date, :categories, presence: true
  validate :end_cannot_come_before_start
  validates :limit, numericality: {greater_than: 0}
  scope :active, -> { where("start_date <= ? AND end_date > ?", Date.current, Date.current) }
  scope :inactive, -> { where("start_date > ?", Date.current) }
  scope :completed, -> { where("end_date <= ?", Date.current) }

  # custom nested params to ensure that users can edit category names properly through the budget update route or otherwise create a new category
  def categories_attributes=(attributes)
    attributes.each do |index, attribute|
      unless attribute[:title].blank? || self.categories.map(&:title).include?(attribute[:title])
        existing_category = self.categories[index.to_i]
        if existing_category == nil
          new_category = Category.create(title: attribute[:title])
          self.categories << new_category
        else
          existing_category.update(title: attribute[:title])
        end
      end
    end
  end

  def remaining_expense
    self.limit - self.total_expense
  end

  def exceeded?
    self.total_expense > self.limit
  end

  def average_expenditure
    if Date.current > self.end_date
      #completed budget
      self.total_expense / (self.end_date - self.start_date).to_i
    else
      #active budget
      # total expense / days passed, in case of first day, just behave as if 1 day has passed, i.e. show total expense
      Date.current > self.start_date ? self.total_expense / (Date.current - self.start_date).to_i : self.total_expense
    end
  end

  def recommended_expenditure
    if Date.current > self.start_date
      #active budget
      self.remaining_expense/self.remaining_days
    else
      #inactive budgets
      self.remaining_expense / (self.end_date - self.start_date).to_i
    end
  end

  def remaining_days
    (self.end_date - Date.current).to_i
  end

  def ordered_categories
    self.categories.order(:subtotal => :desc)
  end

  def top_five_expenses
    self.expenses.order(:cost => :desc).limit(5)
  end

  def most_recent_expenses
    self.expenses.order(:created_at => :desc).limit(5)
  end

  def status
    if self.start_date > Date.current
      "Inactive"
    elsif self.end_date <= Date.current
      "Complete"
    else
      "Active"
    end
  end

  private

  def end_cannot_come_before_start
    unless self.end_date == nil or self.start_date == nil
      errors.add(:end_date, "cannot come before start date") if self.end_date < self.start_date
    end
  end

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_time_zone
  before_action :set_and_authorize_budget, except: [:index, :new, :create]

  def index
    respond_to do |f|
      f.html
      f.json { render :json => { active: current_user.budgets.active, inactive: current_user.budgets.inactive,  completed: current_user.budgets.completed } }
    end
  end

  def new
    @budget = current_user.budgets.build
    render layout: false
  end

  def create
    @budget = current_user.budgets.build(budget_params)
    @budget.save ? (render :show, layout: false, status: 201) : (render :new, layout: false, status: 422)
  end

  def show
    render layout: false
  end

  def edit
    render layout: false
  end

  def update
    @budget.update(budget_params) ? (render :show, layout: false) : (render :edit, layout: false, status: 422)
  end

  def destroy
    @budget.destroy
    redirect_to user_budgets_path
  end

  private

  def set_and_authorize_budget
    @budget = Budget.find(params[:id])
    authorize @budget
  end

  def budget_params
    params.require(:budget).permit(:name, :start_date, :end_date, :limit, :categories_attributes => [:title])
  end

  # Ensure that users are not able to interact with budgets until they have timezones in order to avoid issues with dates.

  def require_time_zone
    redirect_to edit_user_time_zone_path, :alert => "Please set your timezone." unless current_user.time_zone
  end

end

app/helpers/budgets_helper.rb
module BudgetsHelper

  def budget_categories(budget)
    while budget.categories.length < 10 do
      budget.categories.build
    end
    budget.categories
  end

  def show_budget_status(budget)
    if budget.status == "Inactive"
      "This budget is not yet active. It starts at #{budget.start_date.strftime("%B %e, %Y")} and ends at #{budget.end_date.strftime("%B %e, %Y")}."
    elsif budget.status == "Complete"
      "This budget has been completed. It started at #{budget.start_date.strftime("%B %e, %Y")} and ended at #{budget.end_date.strftime("%B %e, %Y")}."
    else
      "Budget in progress with #{pluralize(budget.remaining_days, 'day')} left. It started at #{budget.start_date.strftime("%B %e, %Y")} and ends at #{budget.end_date.strftime("%B %e, %Y")}."
    end
  end

  def show_budget_recommendation(budget)
    if budget.status == "Inactive"
      "Once your budget begins, you can spend up to #{number_to_currency(budget.recommended_expenditure)} on a daily basis."
    elsif budget.status == "Complete"
      "Your average daily expenditure was #{number_to_currency(budget.average_expenditure)}."
    else
      "Your current average of daily expenses is #{number_to_currency(budget.average_expenditure)}. In order to meet your budget goals, you can spend up to
        #{number_to_currency(budget.recommended_expenditure)} on a daily basis."
    end
  end


end

app/views/budgets/_categories.html.erb
<table class="table">
  <thead>
    <tr>
      <th class="col-md-3">Category</th>
      <th class="col-md-3">% of Expenditure Limit</th>
      <th class="col-md-3">% of Current Expenditure</th>
      <th class="col-md-1">Subtotal</th>
    </tr>
  </thead>
  <tbody>
    <% categories.each do |category| %>
      <tr>
        <th scope="row" class="category"><%= link_to category.title, category_path(category) %></th>
        <td><%= number_to_percentage(category.total_percentage, precision: 0)%></td>
        <td><%= number_to_percentage(category.current_percentage, precision: 0)%></td>
        <td><%= number_to_currency(category.subtotal) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/budgets/_expenses.html.erb
<table class="table">
  <thead>
    <tr>
      <th class="col-md-3">Category</th>
      <th class="col-md-3">Description</th>
      <th class="col-md-3">% of Category Subtotal</th>
      <th class="col-md-1">Cost</th>
    </tr>
  </thead>
  <tbody>
    <% expenses.each do |expense| %>
      <tr>
        <th scope="row" class="category"><%= link_to expense.category.title, category_path(expense.category) %></th>
        <td><%= expense.description %></td>
        <td><%= number_to_percentage(expense.category_percentage, precision: 0)%></td>
        <td><%= number_to_currency(expense.cost) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/budgets/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for budget do |f| %>
      <% if budget.errors.any? %>
        <div id="error_explanation">
          <h2>Please enter valid information.</h2>

          <ul>
            <% budget.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">

        <div class="field">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, class: "form-control", placeholder: "YYYY-MM-DD" %>
        </div>

        <div class="field">
          <%= f.label :end_date %>
          <%= f.date_field :end_date, class: "form-control", placeholder: "YYYY-MM-DD" %>
        </div>


        <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control"%>
        </div>

        <div class="field">
        <%= f.label :limit %>
        <%= f.text_field :limit, class: "form-control" %>
        </div>

        <%= f.fields_for :categories, budget_categories(budget) do |categories_fields| %>
        <div class="field">
             <%= categories_fields.label :category %>
             <%= categories_fields.text_field :title, class: "form-control" %>
           </div>

        <% end %>

      </div>

      <div class="actions">
      <%= f.submit class: "btn btn-default btn-block" %>
      </div>

    <% end %>
  </div>
</div>

app/views/budgets/edit.html.erb
<h1>Edit Specifications</h1>

<%= render partial: "budgets/form", locals: {budget: @budget} %>

app/views/budgets/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="new_budget"><%= link_to "Create a New Budget", new_budget_path %></h2>
    <br>
    <div class=budget_link>
      <div id="active">

      </div>

      <br>
      <div id="inactive">

      </div>

      <br>
      <div id="completed">

      </div>
    </div>


  </div>
</div>


<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $.ajaxSetup({ cache: false });
    populateIndex();
    bindBudgetNewLink();
  });
</script>

app/views/budgets/new.html.erb
<h1>Budget Specifications</h1>

<%= render partial: "budgets/form", locals: {budget: @budget} %>

app/views/budgets/show.html.erb
  <h1>Expense Report for <%= @budget.name %></h1>
  <h4><%= show_budget_status(@budget) %></h4>
  <h4 class="edit_budget"><%= link_to "Edit Budget Specifications", edit_budget_path(@budget) %></h4>
  <h4 class="warning"><%= link_to "Delete Budget", budget_path(@budget), :method => :delete %></h4>
  <% if @budget.exceeded? %>
    <h3 class="warning">Budget Has Been Exceeded</h3>
  <% end %>

  <br>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">



      <h4>Expenditure Limit: <%= number_to_currency(@budget.limit) %></h4>
      <h4>Current Expenditure: <%= number_to_currency(@budget.total_expense) %></h4>
      <h4>Remaining Expenditure: <%= number_to_currency(@budget.remaining_expense) %></h4>

      <br>
      <p><%= show_budget_recommendation(@budget) %></p>

      <p> Add and delete expenses by clicking on one of the categories below.</p>
      <h3> Categorical Breakdown </h3>

        <%= render partial: "budgets/categories", locals: { categories: @budget.ordered_categories } %>

      <h3> Top Five Expenses </h3>
        <%= render partial: "budgets/expenses", locals: { expenses: @budget.top_five_expenses } %>

      <h3> Most Recent Expenses </h3>
        <%= render partial: "budgets/expenses", locals: { expenses: @budget.most_recent_expenses } %>

    </div>
  </div>