config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks" }
  resource :user, only: [] do
    resources :budgets, only: [:index]
  end
  get 'user/timezone', to: 'users#edit', as: 'edit_user_time_zone'
  resources :users, only: [:update]

  resources :budgets, only: [:new, :create, :show, :edit, :update, :destroy]

  resources :categories, only: [:destroy, :show] do
    resources :expenses, only: [:create, :new]
  end

  resources :expenses, only: [:destroy]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Budget Management System", user_budgets_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to current_user.email, user_budgets_path%> </li>
      <li><%= link_to "Budgets", user_budgets_path %></li>
        <li><%= link_to "Set Timezone", edit_user_time_zone_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Log In With GitHub", user_github_omniauth_authorize_path %>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_notifications.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p class="notice"><%= notice %></p>
    <p class="alert" id="bootstrap-override"><%= alert %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <%= render 'layouts/notifications' %>
    <div id="content">
      <%= yield %>
    </div>
  </div>
</body>
</html>